const data = {
  products: [
    {
      id: "1",
      name: "Nike Tshirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      stock: 10,
      brand: "Nike",
      rating: "3.5",
      numReview: 10,
      description: "High quality product",
    },
    {
      id: "2",
      name: "Nike2 Tshirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 121,
      stock: 10,
      brand: "Nike",
      rating: "4.5",
      numReview: 10,
      description: "High quality product",
    },
    {
      id: "3",
      name: "Nike3 Tshirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 122,
      stock: 10,
      brand: "Nike",
      rating: "4.5",
      numReview: 10,
      description: "High quality product",
    },
    {
      id: "4",
      name: "Nike4 Tshirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 123,
      stock: 10,
      brand: "Nike",
      rating: "4.5",
      numReview: 10,
      description: "High quality product",
    },
    {
      id: "5",
      name: "Nike5 Tshirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 124,
      stock: 10,
      brand: "Nike",
      rating: "4.5",
      numReview: 10,
      description: "High quality product",
    },
    {
      id: "6",
      name: "Nike6 Tshirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 125,
      stock: 0,
      brand: "Nike",
      rating: "4.5",
      numReview: 10,
      description: "High quality product",
    },
  ],
};

export default data;
